const constants = {

    //teacher
    REGISTER_TEACHER: 'REGISTER_TEACHER',
    LOGIN_TEACHER: 'LOGIN_TEACHER',
    LOGOUT_TEACHER: 'LOGOUT_TEACHER',
    SET_TEACHER_ID: 'SET_TEACHER_ID',
    LOAD_TEACHER: 'LOAD_TEACHER',
    LOAD_TEACHER_DATA: 'LOAD_TEACHER_DATA',

    //modals
    OPEN_REGISTER: 'OPEN_REGISTER',
    CLOSE_REGISTER: 'CLOSE_REGISTER',
    OPEN_LOGIN: 'OPEN_LOGIN',
    CLOSE_LOGIN: 'CLOSE_LOGIN'
}

export default constants